CC = gcc
CFLAGS = -Wall -Werror -Wextra -pedantic -std=gnu89

main: 7-main.c
	$(CC) $(CFLAGS) 7-main.c 7-insert_dnodeint.c 0-print_dlistint.c 2-add_dnodeint.c 3-add_dnodeint_end.c 4-free_dlistint.c -o 7-main && ./7-main